### PR TITLE
Update alpine to 3.14

### PR DESCRIPTION
**Pull request by vkatsuba**
* [Alpine 3.14.0](https://www.alpinelinux.org/posts/Alpine-3.14.0-released.html)
* [Release Notes](https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0)

### CODE REVIEW

**Comment by ebengt** [comment]
This version (3.14) might create problems with SCTP on older Linux kernels. We might need to document this.

**Comment by vkatsuba** [comment]
> This version (3.14) might create problems with SCTP on older Linux kernels. We might need to document this.

This problems are related only to `3.14` or to `3.13` too?

**Comment by ebengt** [comment]
Good question. I do not know.

I think this repo is used to create images for deploying Erlang in clusters.
Therefore some documentation about missing functionality due to differernt Linux kernel versions is a good idea.

**Comment by RoadRunnr** [comment]
We explicitly pull in the older kernel headers to avoid the SCTP problems. The switch to newer Alpine should therefore be safe.

**Review by RoadRunnr — APPROVED** [review]

**Comment by ebengt** [comment]
Yes, we install linux-headers=5.4.5-r1. I think that means we need Linux 5.4+,
Based upon https://github.com/travelping/smc/blob/main/docs/operations.md, table Supported OS

**Comment by RoadRunnr** [comment]
4.12 should be oldest supported kernel with the 5.4 kernel headers. But that has not been tested.

**Comment by ebengt** [comment]
CDF to the rescue. The dockerfile says:
FROM quay.io/travelping/alpine-erlang:23.3 AS build-env
and later
FROM alpine:3.12

That image has been tested on our OpenShift cluster. SCTP does not work.

**Comment by RoadRunnr** [comment]
That is a strange combination. The Erlang image was build on alpine, switching to 3.12 in the final image can introduce problems.

I any case, if OpenShift is that broken, then RedHat should better fix their stuff.

**Comment by ebengt** [comment]
I used 3.12 since it has been good for SCTP in production clusters. But I could change to 3.14? 3.13?

**Pull request merged**
